### ISSUE TITLE
legibility of figure .highlight .nt very difficult to read against #111 background

### ISSUE THREAD

**Issue by guylyons** [revel/revel.github.io#146]
the syntax theme for the site uses jekyll-github.css, which looks great against its default #f8f8f8 background-color, but there is an overriding background color of #111 which makes the .highlight .nt, which is navy, very difficult to read.

is there any interest in changing this to improve the legibility?

see for example: http://revel.github.io/tutorial/firstapp.html

**Comment by pedromorgan** [comment]
Its because the background-color is not black (which I dont like personally)

**Comment by guylyons** [comment]
https://www.dropbox.com/s/qchgx3zdissy7gh/Screenshot%202017-09-11%2015.08.04.png?dl=0

**Comment by notzippy** [comment]
Should be fixed now - but could use some more styling...
