### ISSUE TITLE
Issue with Hello World App docs

### ISSUE THREAD

**Issue by staylorx** [revel/revel.github.io#152]
While running through the tutorial and [Hello World App](http://revel.github.io/tutorial/firstapp.html), I get:
    
    Not Found
    No matching route found:  /App/Hello?myName=Steve

I have changed the controller and added the html file in the App folder. Something mismatched with a new version? 

I'm on go version go1.9.2 windows/amd64.

Thanks!

**Comment by notzippy** [comment]
Sorry for the delayed response, this is because the routes file no longer has the wildcard route. The tutorial has been updated and should work properly now
