### ISSUE TITLE
Missing Namespace manual page

### ISSUE THREAD

**Issue by brendensoares** [revel/revel.github.io#162]
http://revel.github.io/manual/namespace.html 404
from http://revel.github.io/manual/concepts.html
https://github.com/revel/revel.github.io/search?utf8=%E2%9C%93&q=namespace&type=
there is no namespace manual page

**Comment by notzippy** [comment]
resolved, thanks !

**Comment by pedromorgan** [comment]
@notzippy rocking.. cool stiuff reality check https://www.youtube.com/watch?v=5fS7CV5s0hw

**Comment by notzippy** [comment]
That is scarey, next thing you know they will develop a google home app
that somehow automatically performs some action based on this....
