### ISSUE TITLE
Where to put 'user-id' of authenticated user

### ISSUE THREAD

**Issue by Orxcle-xx** [revel/revel.github.io#185]
Hi,

Happy New Year and thanks for great framework!

I am building an API using Revel and want to secure it using token mechanism.
I want something simple ( I don't need role based ) and powerful at the same time.
So I created a simple config file, where routes and policies ( anonymous / authorized ) are defined.

Then I use revel.InterceptMethod(authmodule.Secure, revel.BEFORE) to validate each request for proper token.
After the user is successfully validated, I want to put his 'userId' somewhere so I could use it in controllers.  I don't think session is a good place as all my servers are stateless and authentication token is sent with each http request.

What is the best place to put it?

Thank you in advance!

**Comment by notzippy** [comment]
Hi - If you want the user id to be accessible by the controller you can put it in the [controller.args](https://godoc.org/github.com/revel/revel#Controller) that is a scratchpad of mapped data that is not shared per request

**Comment by Orxcle-xx** [comment]
but what if 'userId' parameter will be sent with the request? In this case controller.args will also contain 'userId' value passed by the whoever made the request, right?
