### ISSUE TITLE
spelling error in documentation

### ISSUE THREAD

**Issue by DGKSK8LIFE** [revel/revel.github.io#193]
In the `Config` section of the database section in the documentation, a code example contains a method argument spelling error. Here is an image (error in line 3 of the code): 
![image](https://user-images.githubusercontent.com/45473363/74052488-97956700-499f-11ea-8b71-dc4727b33f88.png)
TL;DR: `localhost` is spelled `locahost`

**Comment by DGKSK8LIFE** [comment]
@brendensoares The PR is here: https://github.com/revel/revel.github.io/pull/194

**Comment by pedromorgan** [comment]
Fixed
