### ISSUE TITLE
Generating godoc files is broken

### ISSUE THREAD

**Issue by brendensoares** [revel/revel.github.io#35]
https://github.com/revel/revel.github.io/blob/master/docfile.go

Seems for go1.3's `godoc` that we can't simple provide 1 template override e.g. `package.html`. It complains that other template are missing.

This is a big issue since we want to enhance our godoc instructions to be as useful as the current manual. The biggest reason we want to do this is so the manual will stay up to date if we don't have to update it separately as the code evolves.

**Comment by brendensoares** [comment]
@pedromorgan it's a manual process https://github.com/revel/revel.github.io/blob/master/docfile.go#L3

**Comment by pedromorgan** [comment]
were moving to revelframework.com so moot and closing
