### ISSUE TITLE
Update template manual page

### ISSUE THREAD

**Issue by brendensoares** [revel/revel.github.io#39]
## TODO

- [x] document [`url` helper](https://github.com/revel/revel/blob/c5893f222a8983e12aaac6ffaac0362ddcc56087/template.go#L46)
- [x] remove `eq`
- [x] update "improve this page" buttons to point to `develop` branch

**Comment by anonx** [comment]
> sometimes the template name is not consistent with the Action

@goofcc If I understand you correctly, `RenderTemplate` is what you need. You can use any template name. Demo:
```
func (c *App) Index() revel.Result {
	c.RenderArgs["whatEverIWant"] = "Something cool to render..."

	return c.RenderTemplate("SomeDirectory/SomeFile.html")
}
```

**Comment by brendensoares** [comment]
@pedromorgan completed this todo list. Thanks!
