### ISSUE TITLE
style + bootstrap

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#42]
- Upgrade to bootstrap 3

**Comment by brendensoares** [comment]
:+1: I'd also like to add support for Foundation CSS.

**Comment by pedromorgan** [comment]
OK,, so one step at a time ...

For now I wanna convert to bootstrap 3, to get it under control..

However I am a bit confused with some issues eg:

- do we really need pretty print ? cant see what this does and commenting it out here has no noticable effect..

- what does journal.min.css do .. is anyone emotionally attached to this ?

- cant see what lang-go-rich.js does..

Anyway commenting out the above has no noticable effects in bootstrap 3

**Comment by brendensoares** [comment]
`prettify.css` is for formatting code for printing. That seems useful.

`journal.min.css` looks like a modified bootstrap theme:
- https://github.com/revel/revel.github.io/blob/master/css/journal.min.css vs. https://github.com/arturadib/strapdown/blob/gh-pages/v/0.1/themes/journal.min.css
- http://bootswatch.com/journal/

`lang-go-rich.js` is a modified Go code highlighter in Javascript
- https://github.com/revel/revel.github.io/blob/master/js/lang-go-rich.js vs. https://code.google.com/p/google-code-prettify/source/browse/trunk/src/lang-go.js

**Comment by pedromorgan** [comment]
Here's a preview of the bootstrap3 theme

Have taken a knife to it.. so expect to put features back in, rather than try and find everything in there.. 

http://revel-docs.daffodil.uk.com/

**Comment by brendensoares** [comment]
We should look into using HighlightJS for code syntax highlighting. I like:
**Monokai Sublime**
[![image](https://cloud.githubusercontent.com/assets/905501/5600918/1677539c-929b-11e4-9078-d3a6661327a1.png)](https://highlightjs.org/?snippet=14&style=5)

and

**Solarized Dark**
[![image](https://cloud.githubusercontent.com/assets/905501/5600915/05af0442-929b-11e4-9815-af31b819987a.png)](https://highlightjs.org/?snippet=14&style=1)

If it's easier, we could try using [some color themes](http://jmblog.github.io/color-themes-for-google-code-prettify/) for what we currently use (Google Code Prettify).

**Comment by pedromorgan** [comment]
ok but that works with "js" and would that mean removing the {highlight} tag ??

just means waking thru all examples, and basically undoing what I done ;-)))

which way do we go ?

**Comment by pedromorgan** [comment]
There again, the js iption is probably more transportable should we move away from jekyll (spits)

**Comment by brendensoares** [comment]
Can you show me where the `highlight` tag is currently?

**Comment by pedromorgan** [comment]
ahem err its everywhere... as I said.. I need to undo//

**Comment by brendensoares** [comment]
Alright, so keep pygments and use one of its themes. The 2 themes I mentioned above are also supported in pygments! http://mottie.github.io/Github-Dark/

- [Monokai Sublime](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/monokai.min.css)
- [Solarized Dark](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/solarized-dark.min.css)

**Comment by brendensoares** [comment]
Looks like what I just linked to doesn't work as I expected. I found another, but it also required some tweaks to render: https://github.com/richleland/pygments-css

We might have to experiment with different options. A dark theme might not fit the rest of the site. A light theme might look better.

Pygments sure seem difficult to customize. Maybe JS would be better. Couldn't be that hard to mass replace all the `highlight` jekyll blocks.

**Comment by pedromorgan** [comment]
What swings it into pygments for me is..
1 - server side so colours  in page the html, particular for print page
2 - no js to get, and no "flash" and change after load processing etc..

Pygments also means we can nuke prettify..

**Comment by pedromorgan** [comment]
Ok se here is an example with no pretty print.. which we can tweak

http://revel-docs.daffodil.uk.com/manual/parameters.html


Also one quetion I keep forgetting to ask..

How are the docs generates, adn server on github.. is this manual, or a github service ??

**Comment by notzippy** [comment]
Docs are generated in advanced with jeykll then the server serves the
static pages

**Comment by pedromorgan** [comment]
So were at bootstrap three..

And server side is parsing using "ruby" and pygments I think...

So we are still bound to github. capabilities for future..

Closing this issue for now, but on horizon is to make it more style, more syntax highlight and links etc...

**Comment by pedromorgan** [comment]
Clocing at bootstrap3 implemented
