### ISSUE TITLE
Godoc upstream

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#46]
Should we not link to documentation at http://godoc.org/github.com/revel/revel
(maybe with a template tag etc to make it easier)
these we can pretty well guarantee are up to date.

Just a thought

**Comment by brendensoares** [comment]
@pedromorgan it's a point we've discussed in the past. The benefit we get from manually generating the docs in this repo is that we can provide a [more understandable table of contents](http://revel.github.io/docs/godoc/index.html) than godoc.org.

It would be great if we could automate the generation of docs in this repo!

**Comment by pedromorgan** [comment]
Yes i agree with the "junderstandable TOC".. 

Am confused how its done, and am using an olde laptop without go/dev enviroment installed (babysitting my aunt)

If u could explain how the "godoc/" stuff is created, that would help.

Also noticed #35

**Comment by brendensoares** [comment]
@pedromorgan in #35 I link to the `docfile.go` line which shows an example of how to use it.

From the `revel.github.io` repo working copy:
```
go run docfile.go -templates ~/Dropbox/Public/revel/docs/godoc -out ~/Dropbox/Public/revel/docs  ~/code/gocode/src/github.com/revel/revel/*.go
```
The first time I used that code file, I had to reverse engineer it, so I agree that we need more clear steps showing exactly how to use it and update the godocs. We should probably consider how to restructure the generated godocs considering our latest re-organization efforts.

**Comment by pedromorgan** [comment]
ok, am investegating..

**Comment by pedromorgan** [comment]
nope, am scratching my head on this..

so I need to generate the "godocs" first, adn then run this docfile.go to do post processing ?

**Comment by brendensoares** [comment]
@pedromorgan the `docfile.go` calls the built-in `go doc` on each file (`~/code/gocode/src/github.com/revel/revel/*.go`) and then saves the outputted HTML (`-out ~/Dropbox/Public/revel/docs`). The godoc templates affect the styling of the HTML output (`-templates ~/Dropbox/Public/revel/docs/godoc`).

Make sense?

**Comment by pedromorgan** [comment]
Ok, here's a bash script..
am confised with all the path et all
https://github.com/pedromorgan/revel.github.io/blob/pedro/make_godoc.sh

**Comment by brendensoares** [comment]
@pedromorgan I think you are using the wrong path: `-templates $GOPATH/**github.com/**revel.github.io/docs/godoc` unless that's where you have that repo checked out.

Does this shell file work?

**Comment by pedromorgan** [comment]
No, shell does not work or am I missong something
https://github.com/pedromorgan/revel.github.io/blob/pedro/make_godoc.sh

```
./make_godoc.sh 
GOPATH=
/home/gogo
2015/01/03 08:22:23 Processing /home/gogo/src/github.com/revel/revel/binder.go
2015/01/03 08:22:23 Writing /home/gogo/src/github.com/revel/revel.github.io/docs/godoc/binder.html
2015/01/03 08:22:23 exit status 1
exit status 1
```
But am confused as..
-out - godocs is the target ???

what is docs/src/* for

Does this mean we have to manually convert each file ..??

**Comment by brendensoares** [comment]
I'll have to test it myself tomorrow, but note: https://github.com/pedromorgan/revel.github.io/blob/pedro/docfile.go#L18-L19 there are 2 flags for the script, `template` and `out`. `out` is where the generated HTML goes. The path you pass in, `$GOPATH/src/github.com/revel/revel/*.go` is where `docfile.go` looks for Go files to generate godocs for.

Hope you can figure it out. Feel free to add debug logs to better understand what the script is doing. Also, make sure your paths are correct.

I'll help more later :)

**Comment by pedromorgan** [comment]
Were already there. .so mark this as done .. phew!
