### ISSUE TITLE
Docs Deploy

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#47]
Couple issues

# Where are the docs build and released?
I assume this is not github pages right ?
So am compeltely perplexed where the docs "compilation" happen, is it on a workstation, server, jenkins ? or compiled by github upon commit ???

# Multiversion
- need to get a grip on versioning, ie master and next
- To deal with this, maybe we copy django and have a current docs, at latest and others in dirs
ie
```
/master/manual/index.html
/0.11/manual/index.html << even a symlink to above
/0.9/manual/index.html << legacy and nuked after 1.5 years
/next/manual/index.html << docs for next version
```

**Comment by pedromorgan** [comment]
Reason that "where its compiled' is important, is that I want to add a few {{revel}} tags and customisatinn.., eg expolring an app structure and highlighting

**Comment by brendensoares** [comment]
@pedromorgan do you mean the godocs? We do that manually on our local workstations.

As far as versioning, do you mean having a Revel doc site that reflects the current `develop` branch changes?

**Comment by pedromorgan** [comment]
I meant the whole revel docs site.. Is it a commit to github and github compiles ?

And yes, having to "directories", one for the master and one for develop

**Comment by brendensoares** [comment]
You can run the site locally following the [README instructions](https://github.com/revel/revel.github.io/blob/master/README.md).

More resources:
- https://help.github.com/categories/github-pages-basics/
- https://gist.github.com/chrisjacob/833223
