### ISSUE TITLE
docs vs modules

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#48]
Am updating docs so need clarifications on a some module issues..

look here http://revel-docs.daffodil.uk.com/manual/modules.html

------------------------------

An empty import path disables the module:

     module.mymodulename =

is that the same as 

     #module.mymodulename = /my/dodgy/mod

Are there any other implications..?? eg not imported etc ??

I assume that what we want is that if the module path not exits crash, and not imported ??

what happens if I import module and invalid path?

**Comment by anonx** [comment]
Hey, @pedromorgan. [Here](https://github.com/revel/revel/blob/c5893f222a8983e12aaac6ffaac0362ddcc56087/revel.go#L288) is a code responsible for loading modules:
```go
func loadModules() {
	for _, key := range Config.Options("module.") {
		moduleImportPath := Config.StringDefault(key, "")
		if moduleImportPath == "" {
			continue
		}

		modulePath, err := ResolveImportPath(moduleImportPath)
		if err != nil {
			log.Fatalln("Failed to load module. Import of", moduleImportPath, "failed:", err)
		}
		addModule(key[len("module."):], moduleImportPath, modulePath)
	}
}
```
So, you are right. `module.mymodulename =` is the same as ` #module.mymodulename = /my/dodgy/mod`. In both cases they are just ignored.

> I assume that what we want is that if the module path not exits crash, and not imported ??

If it doesn't exist locally, `revel run` will crash with the following error:

```sh
~
~ revel! http://revel.github.io
~
2015/01/05 11:17:59 revel.go:297: Failed to load module.  Import of github.com/revel/modules/404 failed: cannot find package "github.com/revel/modules/404" in any of:
	/home/johndoe/.gvm/gos/go1.4/src/github.com/revel/modules/404 (from $GOROOT)
	/home/johndoe/Develop/go/src/github.com/revel/modules/404 (from $GOPATH)
```

**BTW**, Important thing is modules are loaded only once (right after `revel run ...`). Config file is not reloaded after its update.

It is possible to use any dirs as modules even those ones which are not really modules. Just nothing will be imported from them (if they do not follow the required structure).

**Comment by anonx** [comment]
http://revel-docs.daffodil.uk.com/manual/modules.html looks awesome, BTW.

**Comment by brendensoares** [comment]
@anonx @pedromorgan side point, I don't like the new h2 with grey background. Draws too much attention. Also, the h1 bottom border is too thick.

**Comment by brendensoares** [comment]
PS - who will manage the Disqus account?

**Comment by anonx** [comment]
@brendensoares I think `h2`s should draw attention. That simplifies the search of information you need. They could be a little bit lighter, though.
![Initial image](http://i.imgur.com/ifJBdMF.png?1)
vs.
![Lighter background](http://i.imgur.com/f36dGy3.png?1)

@pedromorgan There is a horizontal scrollbar when using 1366x768 display.
![Too wide image](http://i.imgur.com/EPtIIal.png?1)

**Comment by pedromorgan** [comment]
sigh! so many changes to style to make everyone happy ;-)
But willl change later..

Re disqus, I stuck that on there to demonstrate.. If you want to use disqus then I need to add some moderators which needs a disqus username.. unless u have an account already...

**Comment by brendensoares** [comment]
@anonx lighter `h2`s look better.

@pedromorgan once we get the website content stable, we should look into responsive styling e.g. image fitting into the viewport.

**Comment by pedromorgan** [comment]
Would prefer to have a "live" site running it...
eg bookings.revel.com

**Comment by pedromorgan** [comment]
Moot
