### ISSUE TITLE
TODO: render

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#49]
Explain more abounr c.Render()

explain c.RenderTemplate()

Also demo RenderText()

**Comment by pedromorgan** [comment]
Also add template quickstart

**Comment by brendensoares** [comment]
revel/revel#235

**Comment by pedromorgan** [comment]
I think the render docs are clearer now it links..
So closing this for now.. and a new issue if its "still and issue"..

**Comment by pedromorgan** [comment]
http://revel.github.io/manual/results.html
