### ISSUE TITLE
TODO: Explain Skel

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#50]
Explain the skeleton more..

the controlers and the fact its used in modulles..

and closelly intertwined

**Comment by pedromorgan** [comment]
Ie the same structure..

**Comment by pedromorgan** [comment]
We need a "skeleton" page.. 
and a simple description of how it works and the modules also etc..

Also My "itch".. it to create the
ggh.com/revel/coffins - skel - skeletons - template whatever..
which is basic boiler plate..

**Comment by Fyb3roptik** [comment]
I am currently using revel in my startup company to run our API. It is working great and would love to help where I can! I can throw together a boilerplate API setup?

**Comment by notzippy** [comment]
I am closing this, as we are developing a new cli tool for revel which will incorporate this better
