### ISSUE TITLE
Use godoc.com, abandon inbuilt godoc

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#52]
I've just been playing around with a script to examine the output..

My conclusion is that it gonna be a pain in the butt.. for example linking from the test suite to an url.Values, calls  /pkg/net/url/#Values

I understand that we want the stuff to look nice in revel manual, and no one as much as myself, but i prefer the easier (and maybe more complicant option), instead of having to maintain also...

As far as the "page goes".. I call it the "api-docs" page..
and I think we would just links to all the revel core, modules, etc.. third parties.. or godocs..

**Comment by brendensoares** [comment]
The only benefit to do the godoc manually is that we can have a custom and more understandable table of contents into the code docs: http://revel.github.io/docs/godoc/index.html

**Comment by pedromorgan** [comment]
Precisely..

But if we move to an appliocation, then we can probably query this data live and self generating index..

Actually thats another think the annoys me..
is when hardcoded links head off to a function on a future/past version..

and its still the one everyone links to.. and no redirect etc... 

eg
redirecting modules/testrunner to github.com/revel/blade-runner

**Comment by pedromorgan** [comment]
Ok so I am in conflict with myself !!!

also #64 

Snag is we:
- want "live docs" from godoc .org
but also future and legacy docs also for the golang api..

Need to look more into godoc and become an expert somehow .. sigh! yet anothe rdocs problem, again after all these f*** years...

**Comment by notzippy** [comment]
build the docs using revel and [blackfriday](https://github.com/russross/blackfriday) , mirror the site to github. Why become an expert in jekyel ?

**Comment by pedromorgan** [comment]
precisely..
and started here..
https://github.com/pedromorgan/revel-www

But guys I need help with that..
1) am not a golang expert and
2) blackfriday we need somw template tags also..

I think that is the route we wanna go down, cos bumping into walls atmo

**Comment by pedromorgan** [comment]
This is mainly done.. maybe a few "hangers" around...
