### ISSUE TITLE
TODO: Quickstart

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#58]
Need to rip the quickstart from @notzippy 

http://reveldoc.notzippy.com/quickstart/

Assumed target is 

quickstart/

**Comment by notzippy** [comment]
Did you want a PR ?

**Comment by brendensoares** [comment]
Any progress here? @pedromorgan @notzippy

**Comment by notzippy** [comment]
Waiting on @pedromorgan response to question...

**Comment by pedromorgan** [comment]
Sorry folks, kinda busy, but a PR would be cool.
