### ISSUE TITLE
Docs for past releases

### ISSUE THREAD

**Issue by brendensoares** [revel/revel.github.io#64]
One thing that has been frustrating while using Ember JS is that their doc website only shows the latest version of the docs. My company doesn't update its 3rd party libraries often and so we aren't always using the latest code. I need to see the correct docs for my version

Revel, I'm sure, will have the same issue. We need to make past versions of the docs viewable.

@pedromorgan Thoughts?

**Comment by pedromorgan** [comment]
This is precisely the point I have been trying to make with 
- problem with github is only current
- problem with godoc its only current..
Thats why ideally we need to "spool" the stuff out to a 
/v234/  also /latest/
/v123/
etc to solve this "future" problem

django docs have it sorted with a dropdown for version..
and also "added in x versioN" and "depreciated" in x version
https://docs.djangoproject.com/en/1.7/

Halleluiah.. brendan gets it ;-)))))))))))))

**Comment by brendensoares** [comment]
@pedromorgan :+1:

**Comment by pedromorgan** [comment]
Ok so got a view on this which is serilising out the docs, and in 1.3/ etc ..

But a drop down we get
[1.999 - latest]
[0.3 - earlier this year]
[0.2 - 2014]

We need to ensure our end users are aware we are gonna break thing,..
for the better..

**Comment by pedromorgan** [comment]
BUT, we also want to maintain back.. which is my position atmo..

**Comment by pedromorgan** [comment]
This is also an issue with golang and menas using "tags" apparently..

**Comment by brendensoares** [comment]
menas?

**Comment by pedromorgan** [comment]
Ok colosing this cos were moving forwardzz.. >>
