### ISSUE TITLE
revelframework.com

### ISSUE THREAD

**Issue by pedromorgan** [revel/revel.github.io#97]
This is the way we wanna go from now.. imho..

I just done an update, and jekyll/etc is complaing and cant compile..

So stuff jekyll.. lets move on to revel on revel please..
and from 
https://github.com/revel/revelframework.com/tree/rf-site

**Comment by pedromorgan** [comment]
dog is hungry

**Comment by brendensoares** [comment]
## TODO

1. ???

**Comment by pedromorgan** [comment]
Moot
